/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.equipo4bda.tutiketapp.gui;

/**
 *
 * @author lui
 */
public class PantallaSaldos extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(PantallaSaldos.class.getName());

    /**
     * Creates new form PantallaSaldos
     */
    public PantallaSaldos() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblTítuloSaldoCuentas = new javax.swing.JLabel();
        lblDescripcion = new javax.swing.JLabel();
        jPSaldoDisponible = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        lblSaldoDisponible = new javax.swing.JLabel();
        pnlCuentasVinculadas = new javax.swing.JPanel();
        lblCuentasVinculadas = new javax.swing.JLabel();
        lblNCuentas = new javax.swing.JLabel();
        pnlMisCuentas = new javax.swing.JPanel();
        lblMisCuentas = new javax.swing.JLabel();
        btnVincularCuenta = new javax.swing.JButton();
        lblCuenta = new javax.swing.JLabel();
        lblSaldo = new javax.swing.JLabel();
        lblBanco = new javax.swing.JLabel();
        lblCuenta1 = new javax.swing.JLabel();
        lblSaldo1 = new javax.swing.JLabel();
        lblBanco1 = new javax.swing.JLabel();
        lblCuenta2 = new javax.swing.JLabel();
        lblSaldo2 = new javax.swing.JLabel();
        lblBanco2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lblTítuloSaldoCuentas.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        lblTítuloSaldoCuentas.setText("Saldo y Cuentas Bancarias");

        lblDescripcion.setForeground(new java.awt.Color(153, 153, 153));
        lblDescripcion.setText("Consulta tu saldo disponible, cuentas vinculadas y movimientos recientes");

        jPSaldoDisponible.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setText("$00000.00 MXN");

        javax.swing.GroupLayout jPSaldoDisponibleLayout = new javax.swing.GroupLayout(jPSaldoDisponible);
        jPSaldoDisponible.setLayout(jPSaldoDisponibleLayout);
        jPSaldoDisponibleLayout.setHorizontalGroup(
            jPSaldoDisponibleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPSaldoDisponibleLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addContainerGap(148, Short.MAX_VALUE))
        );
        jPSaldoDisponibleLayout.setVerticalGroup(
            jPSaldoDisponibleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPSaldoDisponibleLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addContainerGap(48, Short.MAX_VALUE))
        );

        lblSaldoDisponible.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblSaldoDisponible.setText("Saldo disponible:");

        pnlCuentasVinculadas.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        lblCuentasVinculadas.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblCuentasVinculadas.setText("Cuentas vinculadas:");

        lblNCuentas.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        lblNCuentas.setText("0");

        javax.swing.GroupLayout pnlCuentasVinculadasLayout = new javax.swing.GroupLayout(pnlCuentasVinculadas);
        pnlCuentasVinculadas.setLayout(pnlCuentasVinculadasLayout);
        pnlCuentasVinculadasLayout.setHorizontalGroup(
            pnlCuentasVinculadasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlCuentasVinculadasLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlCuentasVinculadasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblCuentasVinculadas)
                    .addComponent(lblNCuentas))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnlCuentasVinculadasLayout.setVerticalGroup(
            pnlCuentasVinculadasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlCuentasVinculadasLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblNCuentas)
                .addGap(18, 18, 18)
                .addComponent(lblCuentasVinculadas)
                .addContainerGap())
        );

        pnlMisCuentas.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        lblMisCuentas.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblMisCuentas.setText("Mis Cuentas Vinculadas");

        btnVincularCuenta.setText("Vincular cuenta");

        lblCuenta.setText("Cuenta: ");

        lblSaldo.setText("0000");

        lblBanco.setText("Banco");

        lblCuenta1.setText("Cuenta: ");

        lblSaldo1.setText("0000");

        lblBanco1.setText("Banco");

        lblCuenta2.setText("Cuenta: ");

        lblSaldo2.setText("0000");

        lblBanco2.setText("Banco");

        javax.swing.GroupLayout pnlMisCuentasLayout = new javax.swing.GroupLayout(pnlMisCuentas);
        pnlMisCuentas.setLayout(pnlMisCuentasLayout);
        pnlMisCuentasLayout.setHorizontalGroup(
            pnlMisCuentasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlMisCuentasLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(pnlMisCuentasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlMisCuentasLayout.createSequentialGroup()
                        .addComponent(lblSaldo)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(pnlMisCuentasLayout.createSequentialGroup()
                        .addGroup(pnlMisCuentasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblMisCuentas)
                            .addGroup(pnlMisCuentasLayout.createSequentialGroup()
                                .addComponent(lblCuenta)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lblBanco)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 475, Short.MAX_VALUE)
                        .addComponent(btnVincularCuenta)
                        .addGap(15, 15, 15))
                    .addGroup(pnlMisCuentasLayout.createSequentialGroup()
                        .addGroup(pnlMisCuentasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblSaldo2)
                            .addGroup(pnlMisCuentasLayout.createSequentialGroup()
                                .addComponent(lblCuenta2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lblBanco2))
                            .addComponent(lblSaldo1)
                            .addGroup(pnlMisCuentasLayout.createSequentialGroup()
                                .addComponent(lblCuenta1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lblBanco1)))
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        pnlMisCuentasLayout.setVerticalGroup(
            pnlMisCuentasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlMisCuentasLayout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(pnlMisCuentasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblMisCuentas)
                    .addComponent(btnVincularCuenta))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pnlMisCuentasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCuenta)
                    .addComponent(lblBanco))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblSaldo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pnlMisCuentasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCuenta1)
                    .addComponent(lblBanco1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblSaldo1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pnlMisCuentasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCuenta2)
                    .addComponent(lblBanco2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblSaldo2)
                .addContainerGap(33, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(47, 47, 47)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblSaldoDisponible)
                    .addComponent(lblDescripcion)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(pnlCuentasVinculadas, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jPSaldoDisponible, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(pnlMisCuentas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblTítuloSaldoCuentas))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(lblTítuloSaldoCuentas)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblDescripcion)
                .addGap(38, 38, 38)
                .addComponent(lblSaldoDisponible)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPSaldoDisponible, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(pnlCuentasVinculadas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(pnlMisCuentas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(47, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new PantallaSaldos().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnVincularCuenta;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPSaldoDisponible;
    private javax.swing.JLabel lblBanco;
    private javax.swing.JLabel lblBanco1;
    private javax.swing.JLabel lblBanco2;
    private javax.swing.JLabel lblCuenta;
    private javax.swing.JLabel lblCuenta1;
    private javax.swing.JLabel lblCuenta2;
    private javax.swing.JLabel lblCuentasVinculadas;
    private javax.swing.JLabel lblDescripcion;
    private javax.swing.JLabel lblMisCuentas;
    private javax.swing.JLabel lblNCuentas;
    private javax.swing.JLabel lblSaldo;
    private javax.swing.JLabel lblSaldo1;
    private javax.swing.JLabel lblSaldo2;
    private javax.swing.JLabel lblSaldoDisponible;
    private javax.swing.JLabel lblTítuloSaldoCuentas;
    private javax.swing.JPanel pnlCuentasVinculadas;
    private javax.swing.JPanel pnlMisCuentas;
    // End of variables declaration//GEN-END:variables
}
