/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.equipo4bda.tutiketapp.gui;

/**
 *
 * @author lui
 */
import com.equipo4bda.tutiketapp.negocio.CuentaCliente;
import com.equipo4bda.tutiketapp.negocio.Evento;
import com.equipo4bda.tutiketapp.negocio.GestorCuentas;
import com.equipo4bda.tutiketapp.negocio.SesionActual;
import com.equipo4bda.tutiketapp.negocio.SesionUsuario;
import java.util.List;
import javax.swing.JOptionPane;
import com.equipo4bda.tutiketapp.negocio.GestorCompras;
import java.math.BigDecimal;
public class PantallaCompra extends javax.swing.JFrame {
    private final GestorCompras gestorCompras = new GestorCompras();
    private final GestorCuentas gestorCuentas = new GestorCuentas();
    private List<CuentaCliente> cuentas;
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(PantallaCompra.class.getName());

    /**
     * Creates new form PantallaCompra
     */
    public PantallaCompra() {
        initComponents();
        cargarEvento();
        cargarCuentas();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        lblTituloCompra = new javax.swing.JLabel();
        lblLeyendaCompra = new javax.swing.JLabel();
        lblTituloEvento = new javax.swing.JLabel();
        lblEventoSeleccionado = new javax.swing.JLabel();
        lblIDEvento = new javax.swing.JLabel();
        lblLugarEvento = new javax.swing.JLabel();
        lblPrecioEvento = new javax.swing.JLabel();
        lblCantidadBoletos = new javax.swing.JLabel();
        cmbCantidad = new javax.swing.JComboBox<>();
        lblCuentaBancaria = new javax.swing.JLabel();
        cmbCuenta = new javax.swing.JComboBox<>();
        lblCVV = new javax.swing.JLabel();
        pwdCVV = new javax.swing.JPasswordField();
        jPanel2 = new javax.swing.JPanel();
        lblSubtotal = new javax.swing.JLabel();
        lblCargoServicio = new javax.swing.JLabel();
        lblTotal = new javax.swing.JLabel();
        lblSubtotalPesos = new javax.swing.JLabel();
        lblCargoServicioPesos = new javax.swing.JLabel();
        lblTotalPesos = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel1.setText("TiketFan");

        jPanel1.setBorder(new javax.swing.border.MatteBorder(null));

        lblTituloCompra.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblTituloCompra.setText("Realizar la Compra");

        lblLeyendaCompra.setForeground(new java.awt.Color(102, 102, 102));
        lblLeyendaCompra.setText("Confirma tu selección y completa los datos de pago");

        lblTituloEvento.setFont(new java.awt.Font("Segoe UI", 1, 8)); // NOI18N
        lblTituloEvento.setText("EVENTO SELECCIONADO");

        lblEventoSeleccionado.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblEventoSeleccionado.setText("Evento A");

        lblIDEvento.setText("EV-0000");

        lblLugarEvento.setText("Lugar Evento");

        lblPrecioEvento.setText("$000");

        lblCantidadBoletos.setText("Cantidad de boletos:");

        cmbCantidad.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3", "4", "5", "6", "7", "8", "9" }));
        cmbCantidad.addActionListener(this::cmbCantidadActionPerformed);

        lblCuentaBancaria.setText("Cuenta Bancaria a Cargar:");

        cmbCuenta.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Cuenta 1", "Cuenta 2", "Cuenta 3" }));
        cmbCuenta.addActionListener(this::cmbCuentaActionPerformed);

        lblCVV.setText("CVV:");

        pwdCVV.addActionListener(this::pwdCVVActionPerformed);

        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        lblSubtotal.setText("Subtotal:");

        lblCargoServicio.setText("Cargo por Servicio:");

        lblTotal.setText("Total:");

        lblSubtotalPesos.setText("$0");

        lblCargoServicioPesos.setText("$0");

        lblTotalPesos.setText("$0");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblSubtotal)
                    .addComponent(lblTotal)
                    .addComponent(lblCargoServicio))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 172, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblSubtotalPesos)
                    .addComponent(lblCargoServicioPesos)
                    .addComponent(lblTotalPesos))
                .addGap(38, 38, 38))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblSubtotal)
                    .addComponent(lblSubtotalPesos))
                .addGap(33, 33, 33)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCargoServicio)
                    .addComponent(lblCargoServicioPesos))
                .addGap(42, 42, 42)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblTotal)
                    .addComponent(lblTotalPesos))
                .addContainerGap(12, Short.MAX_VALUE))
        );

        jButton2.setText("Comprar");
        jButton2.addActionListener(this::jButton2ActionPerformed);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblTituloCompra)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblLeyendaCompra)
                            .addComponent(lblEventoSeleccionado)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addComponent(lblIDEvento)
                                    .addGap(55, 55, 55)
                                    .addComponent(lblLugarEvento)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(lblPrecioEvento))
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addGap(1, 1, 1)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                            .addComponent(lblCantidadBoletos)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(cmbCantidad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                            .addComponent(lblCuentaBancaria)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(cmbCuenta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(lblTituloEvento)
                                                .addGroup(jPanel1Layout.createSequentialGroup()
                                                    .addComponent(lblCVV)
                                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                    .addComponent(pwdCVV, javax.swing.GroupLayout.PREFERRED_SIZE, 223, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                            .addGap(0, 0, Short.MAX_VALUE))))))))
                .addGap(23, 23, 23))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jButton2)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(15, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblTituloCompra)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblLeyendaCompra)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblTituloEvento)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblEventoSeleccionado)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblIDEvento)
                    .addComponent(lblLugarEvento)
                    .addComponent(lblPrecioEvento))
                .addGap(36, 36, 36)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCantidadBoletos)
                    .addComponent(cmbCantidad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(36, 36, 36)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCuentaBancaria)
                    .addComponent(cmbCuenta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCVV)
                    .addComponent(pwdCVV, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 37, Short.MAX_VALUE)
                .addComponent(jButton2)
                .addGap(21, 21, 21))
        );

        jButton1.setText("Volver");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jButton1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel1)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jButton1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cmbCantidadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbCantidadActionPerformed
        actualizarTotales();
    }//GEN-LAST:event_cmbCantidadActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        try {
            SesionUsuario sesion = SesionActual.getSesion();
            Evento evento = SesionActual.getEventoSeleccionado();

            if (sesion == null) {
                JOptionPane.showMessageDialog(this, "No hay una sesión activa.");
                return;
            }

            if (evento == null) {
                JOptionPane.showMessageDialog(this, "No hay un evento seleccionado.");
                return;
            }

            int indiceCuenta = cmbCuenta.getSelectedIndex();

            if (indiceCuenta == -1 || cuentas == null || cuentas.isEmpty()) {
                JOptionPane.showMessageDialog(this, "Selecciona una cuenta bancaria.");
                return;
            }

            String cvv = new String(pwdCVV.getPassword());

            if (!cvv.matches("\\d{3}")) {
                JOptionPane.showMessageDialog(this, "El CVV debe contener exactamente 3 números.");
                return;
            }

            int cantidad = Integer.parseInt(String.valueOf(cmbCantidad.getSelectedItem()));

            if (cantidad > evento.getBoletosDisponibles()) {
                JOptionPane.showMessageDialog(this, "No hay suficientes boletos disponibles.");
                return;
            }

            CuentaCliente cuentaSeleccionada = cuentas.get(indiceCuenta);

            BigDecimal total = gestorCompras.realizarCompra(sesion.getIdUsuario(), cuentaSeleccionada.getIdCuentaCliente(), evento, cantidad);

            JOptionPane.showMessageDialog(this, "Compra realizada correctamente.\nTotal cobrado: $" + total);

            evento.setBoletosDisponibles(evento.getBoletosDisponibles() - cantidad);

            cargarCuentas();

        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, e.getMessage(), "Error de compra", JOptionPane.ERROR_MESSAGE);
    }

    }//GEN-LAST:event_jButton2ActionPerformed

    private void cmbCuentaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbCuentaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmbCuentaActionPerformed

    private void pwdCVVActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pwdCVVActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_pwdCVVActionPerformed
    
    private void cargarEvento() {
        Evento evento = SesionActual.getEventoSeleccionado();

        if (evento == null) {
            JOptionPane.showMessageDialog(this, "No hay un evento seleccionado.");
            return;
        }

        lblEventoSeleccionado.setText(evento.getNombreEvento());
        lblIDEvento.setText("EV-" + evento.getIdEvento());
        lblLugarEvento.setText("N/D");
        lblPrecioEvento.setText("$" + evento.getPrecioBoleto());
    }

    private void actualizarTotales() {
        Evento evento = SesionActual.getEventoSeleccionado();

        if (evento == null) {
            return;
        }

        int cantidad = Integer.parseInt(String.valueOf(cmbCantidad.getSelectedItem()));
        double precio = evento.getPrecioBoleto();

        double subtotal = precio * cantidad;
        double cargoServicio = subtotal * 0.10;
        double total = subtotal + cargoServicio;

        lblSubtotalPesos.setText(String.format("$%.2f", subtotal));
        lblCargoServicioPesos.setText(String.format("$%.2f", cargoServicio));
        lblTotalPesos.setText(String.format("$%.2f", total));
    }
    
    private void cargarCuentas() {
        try {
            SesionUsuario sesion = SesionActual.getSesion();

            if (sesion == null) {
                return;
            }

            cuentas = gestorCuentas.obtenerCuentasCliente(sesion.getIdUsuario());

            cmbCuenta.removeAllItems();

            for (CuentaCliente cuenta : cuentas) {
                cmbCuenta.addItem(cuenta.getBanco() + " - " + cuenta.getNumCuenta() + " - $" + cuenta.getSaldo());
            }

        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Error al cargar cuentas: " + e.getMessage());
        }
}
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new PantallaCompra().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> cmbCantidad;
    private javax.swing.JComboBox<String> cmbCuenta;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel lblCVV;
    private javax.swing.JLabel lblCantidadBoletos;
    private javax.swing.JLabel lblCargoServicio;
    private javax.swing.JLabel lblCargoServicioPesos;
    private javax.swing.JLabel lblCuentaBancaria;
    private javax.swing.JLabel lblEventoSeleccionado;
    private javax.swing.JLabel lblIDEvento;
    private javax.swing.JLabel lblLeyendaCompra;
    private javax.swing.JLabel lblLugarEvento;
    private javax.swing.JLabel lblPrecioEvento;
    private javax.swing.JLabel lblSubtotal;
    private javax.swing.JLabel lblSubtotalPesos;
    private javax.swing.JLabel lblTituloCompra;
    private javax.swing.JLabel lblTituloEvento;
    private javax.swing.JLabel lblTotal;
    private javax.swing.JLabel lblTotalPesos;
    private javax.swing.JPasswordField pwdCVV;
    // End of variables declaration//GEN-END:variables
}
