/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.equipo4bda.tutiketapp.gui;

/**
 *
 * @author lui
 */
import com.equipo4bda.tutiketapp.negocio.GestorAutenticacion;
import com.equipo4bda.tutiketapp.negocio.SesionActual;
import com.equipo4bda.tutiketapp.negocio.SesionUsuario;
import javax.swing.JOptionPane;
public class PantallaInicioSesion extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(PantallaInicioSesion.class.getName());
    private final GestorAutenticacion gestorAutenticacion = new GestorAutenticacion();
    /**
     * Creates new form PantallaInicioSesion
     */
    public PantallaInicioSesion() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblEmail = new javax.swing.JLabel();
        txtEmail = new javax.swing.JTextField();
        lblCotrasena = new javax.swing.JLabel();
        pwdContrasena = new javax.swing.JPasswordField();
        btnConfirmar = new javax.swing.JButton();
        btnRegistrarCliente = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lblEmail.setText("Email");

        txtEmail.addActionListener(this::txtEmailActionPerformed);

        lblCotrasena.setText("Contraseña");

        pwdContrasena.addActionListener(this::pwdContrasenaActionPerformed);

        btnConfirmar.setText("Confirmar");
        btnConfirmar.addActionListener(this::btnConfirmarActionPerformed);

        btnRegistrarCliente.setText("Registrar Cuenta");
        btnRegistrarCliente.addActionListener(this::btnRegistrarClienteActionPerformed);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lblCotrasena)
                    .addComponent(lblEmail)
                    .addComponent(txtEmail)
                    .addComponent(pwdContrasena)
                    .addComponent(btnConfirmar, javax.swing.GroupLayout.DEFAULT_SIZE, 333, Short.MAX_VALUE)
                    .addComponent(btnRegistrarCliente, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(37, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addComponent(lblEmail)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(lblCotrasena)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pwdContrasena, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(57, 57, 57)
                .addComponent(btnConfirmar)
                .addGap(18, 18, 18)
                .addComponent(btnRegistrarCliente)
                .addContainerGap(41, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtEmailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtEmailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtEmailActionPerformed

    private void pwdContrasenaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pwdContrasenaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_pwdContrasenaActionPerformed

    private void btnConfirmarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConfirmarActionPerformed
        try {
           String usuario = txtEmail.getText().trim();
           String contrasena = new String(pwdContrasena.getPassword());

           SesionUsuario sesion = gestorAutenticacion.iniciarSesion(usuario, contrasena);

           SesionActual.setSesion(sesion);

           if (sesion.getTipo() == SesionUsuario.Tipo.CLIENTE) {
               PantallaCatalogo pantalla = new PantallaCatalogo();
               pantalla.setLocationRelativeTo(null);
               pantalla.setVisible(true);
           } else {
               PantallaRendimientoAdmin pantalla = new PantallaRendimientoAdmin();
               pantalla.setLocationRelativeTo(null);
               pantalla.setVisible(true);
           }

           dispose();

       } catch (Exception e) {
           JOptionPane.showMessageDialog(this, e.getMessage(), "Inicio de sesión", JOptionPane.ERROR_MESSAGE);
       }
    }//GEN-LAST:event_btnConfirmarActionPerformed

    private void btnRegistrarClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegistrarClienteActionPerformed
        PantallaRegistro pantalla = new PantallaRegistro();
        pantalla.setLocationRelativeTo(null);
        pantalla.setVisible(true);
    }//GEN-LAST:event_btnRegistrarClienteActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new PantallaInicioSesion().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnConfirmar;
    private javax.swing.JButton btnRegistrarCliente;
    private javax.swing.JLabel lblCotrasena;
    private javax.swing.JLabel lblEmail;
    private javax.swing.JPasswordField pwdContrasena;
    private javax.swing.JTextField txtEmail;
    // End of variables declaration//GEN-END:variables
}
