/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.equipo4bda.tutiketapp.gui;

/**
 *
 * @author lui
 */
import com.equipo4bda.tutiketapp.negocio.Evento;
import com.equipo4bda.tutiketapp.negocio.GestorEventos;
import com.equipo4bda.tutiketapp.negocio.SesionActual;
import com.equipo4bda.tutiketapp.negocio.SesionUsuario;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
public class PantallaCatalogo extends javax.swing.JFrame {
    private final GestorEventos gestorEventos = new GestorEventos();
    private List<Evento> eventos;
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(PantallaCatalogo.class.getName());

    /**
     * Creates new form PantallaCatalogo
     */
    public PantallaCatalogo() {
        initComponents();
        cargarEventos();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        tblEventos = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        lblTituloCatalogo = new javax.swing.JLabel();
        btnSeleccionarEvento = new javax.swing.JButton();
        btnSaldoCuentaws = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Evento", "Tipo", "Edad Min.", "Ubicación", "Precio", "Disponibles"
            }
        ));
        jTable1.setCellSelectionEnabled(true);
        tblEventos.setViewportView(jTable1);
        jTable1.getColumnModel().getSelectionModel().setSelectionMode(javax.swing.ListSelectionModel.SINGLE_INTERVAL_SELECTION);

        lblTituloCatalogo.setFont(new java.awt.Font("Segoe UI", 3, 36)); // NOI18N
        lblTituloCatalogo.setText("Catalogo de Eventos");

        btnSeleccionarEvento.setText("Seleccionar Evento");
        btnSeleccionarEvento.addActionListener(this::btnSeleccionarEventoActionPerformed);

        btnSaldoCuentaws.setText("Saldo y Cuentas");
        btnSaldoCuentaws.addActionListener(this::btnSaldoCuentawsActionPerformed);

        jButton1.setText("Salir");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(tblEventos, javax.swing.GroupLayout.DEFAULT_SIZE, 752, Short.MAX_VALUE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnSaldoCuentaws)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnSeleccionarEvento)))))
                .addGap(22, 22, 22))
            .addGroup(layout.createSequentialGroup()
                .addGap(222, 222, 222)
                .addComponent(lblTituloCatalogo)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(jButton1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblTituloCatalogo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 29, Short.MAX_VALUE)
                .addComponent(tblEventos, javax.swing.GroupLayout.PREFERRED_SIZE, 403, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSeleccionarEvento)
                    .addComponent(btnSaldoCuentaws))
                .addGap(21, 21, 21))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSeleccionarEventoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSeleccionarEventoActionPerformed
        int fila = jTable1.getSelectedRow();

        if (fila == -1) {
            JOptionPane.showMessageDialog(this, "Selecciona un evento.");
            return;
        }

        Evento evento = eventos.get(fila);

        SesionActual.setEventoSeleccionado(evento);

        PantallaCompra pantalla = new PantallaCompra();
        pantalla.setLocationRelativeTo(null);
        pantalla.setVisible(true);
    }//GEN-LAST:event_btnSeleccionarEventoActionPerformed

    private void btnSaldoCuentawsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaldoCuentawsActionPerformed
        PantallaSaldos pantalla = new PantallaSaldos();
        pantalla.setLocationRelativeTo(null);
        pantalla.setVisible(true);
    }//GEN-LAST:event_btnSaldoCuentawsActionPerformed
    
    private void cargarEventos() {
        try {
            eventos = gestorEventos.obtenerEventos();

            DefaultTableModel modelo = (DefaultTableModel) jTable1.getModel();
            modelo.setRowCount(0);

            for (Evento evento : eventos) {
                modelo.addRow(new Object[]{evento.getNombreEvento(), evento.getNombreTipoEvento(), "N/D", "N/D", "N/D", evento.getBoletosDisponibles()});
            }

        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Error al cargar eventos: " + e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
        }
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new PantallaCatalogo().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSaldoCuentaws;
    private javax.swing.JButton btnSeleccionarEvento;
    private javax.swing.JButton jButton1;
    private javax.swing.JTable jTable1;
    private javax.swing.JLabel lblTituloCatalogo;
    private javax.swing.JScrollPane tblEventos;
    // End of variables declaration//GEN-END:variables
}
